/*
 * Created on 26 févr. 2014 ( Time 15:22:53 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.Badge ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity Badge
 * 
 * @author Telosys Tools Generator
 *
 */
public class BadgeValidator extends AbstractValidator<Badge>{

    @Override
    public void validateEntity(Badge entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "badgeNumber", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "authorizationLevel", MessagesKeys.NOT_BLANK);

    }
}