/*
 * Created on 13 janv. 2014 ( Time 12:02:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.validator;

import org.demo.bean.BookOrderItem ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity BookOrderItem
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderItemValidator extends AbstractValidator<BookOrderItem>{

    @Override
    public void validateEntity(BookOrderItem entity, Errors errors) {
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "bookOrderId", MessagesKeys.ID_MUST_DEFINE);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "bookId", MessagesKeys.ID_MUST_DEFINE);

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "quantity", MessagesKeys.NOT_BLANK);
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "price", MessagesKeys.NOT_BLANK);

    }
}