/*
 * Created on 26 févr. 2014 ( Time 15:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.common;


/**
 * Keys constants.
 * 
 * @author Telosys Tools Generator
 *
 */
public class Constants {
	
	public final static String COMPOSITE_KEY_SEPARATOR = "|";

}