/*
 * Created on 20 mars 2014 ( Time 12:14:05 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.common;


/**
 * Keys constants.
 * 
 * @author Telosys Tools Generator
 *
 */
public class Constants {
	
	public final static String COMPOSITE_KEY_SEPARATOR = "|";

}