/*
 * Created on 26 févr. 2014 ( Time 15:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.common;


/**
 * Keys constants for messages.
 * 
 * @author Telosys Tools Generator
 *
 */
public class MessagesKeys {
	
	// Keys for resources messages
	public static final String ID_MUST_DEFINE = "id.must.define";
	public static final String NOT_BLANK = "not.blank";
	
}