/*
 * Created on 26 févr. 2014 ( Time 15:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo;

import javax.servlet.Filter;

import org.springframework.web.filter.HiddenHttpMethodFilter;
import org.springframework.web.multipart.support.MultipartFilter;
import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;

/**
 * WebApp initialization.
 * @author Telosys Tools Generator
 *
 */
public class RestWebApplicationInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
	protected Class<?>[] getRootConfigClasses() {
		return new Class<?>[]{JpaRepositoryConfig.class};
	}

	@Override
	protected Class<?>[] getServletConfigClasses() {
       	return new Class<?>[]{ApplicationConfig.class};
	}

	@Override
    protected String[] getServletMappings() {
        return new String[]{"/"};
    }

    @Override
    protected Filter[] getServletFilters() {
        return new Filter[]{new HiddenHttpMethodFilter(), new MultipartFilter(), new CORSFilter()};
    }
}
