/*
 * Created on 20 mars 2014 ( Time 12:14:05 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Author ;

import org.springframework.data.repository.CrudRepository;



/**
 * Spring JPA Repository for Author
 * 
 * @author Telosys Tools Generator
 *
 */
public interface AuthorRepository extends CrudRepository<Author, Integer> {


}