/*
 * Created on 13 janv. 2014 ( Time 12:02:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Badge ;

import org.springframework.data.repository.CrudRepository;



/**
 * Spring JPA Repository for Badge
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BadgeRepository extends CrudRepository<Badge, Integer> {


}