/*
 * Created on 26 févr. 2014 ( Time 15:22:53 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Book ;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.demo.bean.Author;
import org.demo.bean.Publisher;

import java.util.List;

import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;


/**
 * Spring JPA Repository for Book
 * 
 * @author Telosys Tools Generator
 *
 */
public interface BookRepository extends PagingAndSortingRepository<Book, Integer> {

	@RestResource(rel="byAuthor", path="byAuthor")
	public List<Book> findByAuthor (
			@Param("author") Author author);

	@RestResource(rel="byPublisher", path="byPublisher")
	public List<Book> findByPublisher (
			@Param("publisher") Publisher publisher);


}