/*
 * Created on 26 févr. 2014 ( Time 15:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.EmployeeGroup ;

import org.springframework.data.repository.CrudRepository;

import org.demo.bean.EmployeeGroupKey ;



/**
 * Spring JPA Repository for EmployeeGroup
 * 
 * @author Telosys Tools Generator
 *
 */
public interface EmployeeGroupRepository extends CrudRepository<EmployeeGroup, EmployeeGroupKey> {


}