/*
 * Created on 13 janv. 2014 ( Time 12:02:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Employee ;

import org.springframework.data.repository.CrudRepository;

import org.demo.bean.Shop;
import org.demo.bean.Badge;
import java.util.List;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;


/**
 * Spring JPA Repository for Employee
 * 
 * @author Telosys Tools Generator
 *
 */
public interface EmployeeRepository extends CrudRepository<Employee, String> {

	@RestResource(rel="byShop", path="byShop")
	public List<Employee> findByShop (
			@Param("shop") Shop shop);

	@RestResource(rel="byBadge", path="byBadge")
	public List<Employee> findByBadge (
			@Param("badge") Badge badge);


}