/*
 * Created on 26 févr. 2014 ( Time 15:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Shop ;

import org.springframework.data.repository.CrudRepository;

import org.demo.bean.Employee;
import org.demo.bean.Country;
import java.util.List;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;


/**
 * Spring JPA Repository for Shop
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ShopRepository extends CrudRepository<Shop, String> {

	@RestResource(rel="byEmployee", path="byEmployee")
	public List<Shop> findByEmployee (
			@Param("employee") Employee employee);

	@RestResource(rel="byCountry", path="byCountry")
	public List<Shop> findByCountry (
			@Param("country") Country country);


}