/*
 * Created on 26 févr. 2014 ( Time 15:22:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.repository;

import org.demo.bean.Workgroup ;

import org.springframework.data.repository.CrudRepository;



/**
 * Spring JPA Repository for Workgroup
 * 
 * @author Telosys Tools Generator
 *
 */
public interface WorkgroupRepository extends CrudRepository<Workgroup, Short> {


}